# Generated by Django 3.2.6 on 2024-07-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='user_service_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
