# Generated by Django 3.2.6 on 2024-07-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userpermission_user_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='user_data',
            field=models.JSONField(default={}),
        ),
    ]
