# Generated by Django 3.2.6 on 2024-07-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userpermission_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='approver_user_information_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='requesting_user_information_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
