# Generated by Django 3.2.6 on 2024-07-23 05:14

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_initial_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    # Adding user 2
    user = User(
        first_name="Test",
        last_name="User 1",
        is_active=True,
        is_staff=True,
        is_superuser=True,
        email='test-user-1@test.com',
        username='test-user-1@test.com',
        password=make_password('1234')
    )
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240723_0449'),
    ]

    operations = [
        migrations.RunPython(add_initial_user),
    ]