version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8180:8000"
    volumes:
      - ./user-service:/src
    environment:
      - DATABASE_URL=sqlite:///./test.db

  reservation-service-db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  reservation-web:
    build:
      context: ./reservation-service
    command: sh -c "python /web/manage.py migrate && python /web/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./reservation-service:/web
    ports:
      - "8190:8000"
    depends_on:
      - reservation-service-db
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
  
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "8200:80"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  frontend:
    build:
      context: ./frontend
    ports:
      - "8200:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env

volumes:
  postgres_data: