version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8080:8000"
    volumes:
      - ./user-service:/src
    environment:
      - DATABASE_URL=sqlite:///./test.db