version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8180:8000"
    volumes:
      - ./user-service:/src
    environment:
      - DATABASE_URL=sqlite:///./test.db

  reservation-service:
    reservation-db:
      image: postgres:latest
      environment:
        POSTGRES_DB: mydb
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      volumes:
        - postgres_data:/var/lib/postgresql/data

    reservation-web:
      build:
        context: ./reservation-service
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./reservation-service:/src
      ports:
        - "8190:8000"
      depends_on:
        - reservation-db
      environment:
        - DATABASE_URL=postgres://user:password@reservation-db:5432/mydb
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "8200:80"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: