version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8180:8000"
    volumes:
      - ./user-service:/src
    environment:
      - DATABASE_URL=sqlite:///./test.db

  reservation-service-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  reservation-web:
    build:
      context: ./reservation-service
    command: sh -c "python /web/manage.py migrate && python /web/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./reservation-service:/web
    ports:
      - "8190:8000"
    depends_on:
      - reservation-service-db
    environment:
      PYTHONUNBUFFERED: 1
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgres://user:password@reservation-service-db:5432/mydb
      POSTGRES_HOST: reservation-service-db
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "8200:80"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: